flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
	# Fields
	title = StringField("Title", validators=[DataRequired()])
	content = TextAreaField("Content", validators=[DataRequired()])
		
	# Controlls
	submit = SubmitField('Post')

	

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from flaskblog.config import DATE_FORMAT

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
	form = PostForm()

	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash(f"Your post has been created.", "success")
		return redirect(url_for("main.home"))
	return render_template("create_post.html", title="New Post", form=form, legend="New Post")	


@posts.route("/post/<int:post_id>")
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template("post.html", title=post.title, post=post, format=DATE_FORMAT)	


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)

	if post.author != current_user:
		abort(403)

	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash("Your post has been updated", "success")
		return redirect(url_for("posts.post", post_id=post_id))
	elif request.method == "GET":
		form.title.data = post.title
		form.content.data = post.content
	return render_template("create_post.html", title="New Post", form=form, format=DATE_FORMAT, legend="Update Post")	


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)

	if post.author != current_user:
		abort(403)

	db.session.delete(post)
	db.session.commit()
	flash(f"Your post has been deleted", "success")
	return redirect(url_for("main.home"))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.config import DATE_FORMAT

users = Blueprint("users", __name__)

@users.route("/reg", methods=['GET', 'POST'])
def reg():

	if (current_user.is_authenticated):
		return redirect(url_for("main.home"))

	form = RegistrationForm()

	if form.validate_on_submit() and request.method == "POST":
		try:
			hashed_pass = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
			user = User(username=form.username.data, email=form.email.data, password=hashed_pass)
			db.session.add(user)
			db.session.commit()
			flash(f"Your account has now been created for {form.username.data}. Please login.", "success")
			return redirect(url_for("users.login"))
		except:
			# TODO add logging
			flash("Database error. Contact Administrator", "danger")
	return render_template('reg.html', title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
	form = LoginForm()

	if (current_user.is_authenticated):
		return redirect(url_for("main.home"))

	if form.validate_on_submit() and request.method == "POST":
		user = User.query.filter_by(email=form.email.data).first()

		if user and bcrypt.check_password_hash(user.password, form.password.data) : #(db-pass, form-pass) 
			login_user(user, remember=form.remember.data)
			next_page = request.args.get("next") # Using method instead of accessing the index directly will prevent errors when the dict value is null/nothing/missing
			flash("You have been logged in!", "success")
			return redirect(url_for(next_page)) if next_page else redirect(url_for("main.home"))
		else:
			flash("Login in unsuccessful. Check email and password values.", "danger")

	return render_template('login.html', title="Login", form=form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("main.home"))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():	
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash("Your account information has been updated", "success")
		return redirect(url_for("users.account")) # POST GET redirect pattern
	elif request.method == "GET":
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for("static", filename='profile_pics/' + current_user.image_file)
	print(current_user.image_file)
	return render_template("account.html", title="Account", image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get("page", 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
	return render_template("user_post.html", posts=posts, user=user, format=DATE_FORMAT)

@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():

	if (current_user.is_authenticated):
		return redirect(url_for("main.home"))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash("An email has been sent with instructions to reset your password.", "info")
		return redirect(url_for("users.login"))
	return render_template("reset_request.html", title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):

	if (current_user.is_authenticated):
		return redirect(url_for("main.home"))
	
	user = User.verify_reset_token(token)
	if user is None:
		flash("That is an invalid or expired token", "warning")
		return redirect(url_for("users.reset_request"))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_pass = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
		user.password = hashed_pass
		db.session.commit()
		flash(f"Your password has been updated. Please login.", "success")
		return redirect(url_for("users.login"))
	return render_template("reset_token.html", title="Reset Password", form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}

{% block content %}

	<section class='container'>
		<h2>ABOUT template page</h2>
	</section>

{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- emtpy action means the data will be posted to the same route -->
        <form method="POST" action="" enctype="multipart/form-data"> <!-- enctype is important for passing image information -->
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="mb-4">Account Information</legend>
            <!-- USERNAME -->
            <div class="form-group sp-form">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!-- EMAIL -->
            <div class="form-group sp-form">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!-- PROFILE PICTURE -->
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file form-control-file-style") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class ="form-group sp-form">
            {{ form.submit(class="btn btn-outline-info" )}}
        </div>
    </form>
    <div>
        {% if not current_user.is_authenticated %}
            {# <!-- url_for method is being passed the route METHOD name not the name of the route --> #}
            <small class="text-muted">Already have an account?</small> <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        {% endif %}
    {% endblock content %}

flaskblog/templates/contact.html
{% extends "layout.html" %}

{% block content %}
<h1>Contact</h1>
<div class="content-section">
	Under Construction
</div>

{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<h1>Create Post</h1>
<div class="content-section">
	<!-- emtpy action means the data will be posted to the same route -->
	<form method="POST" action=""> 
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="mb-4">{{ legend }}</legend>

			<!-- TITLE -->
			<div class="form-group sp-form">

				{{ form.title.label(class="form-control-label") }}

				{% if form.title.errors %}
					{{ form.title(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.title.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.title(class="form-control form-control-lg") }}
				{% endif %}

			</div>

			<!-- CONTENT -->
			<div class="form-group sp-form">
				{{ form.content.label(class="form-control-label") }}

				{% if form.content.errors %}
					{{ form.content(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.content.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.content(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class ="form-group sp-form">
			{{ form.submit(class="btn btn-outline-info" )}}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/index.html
{% extends "layout.html" %}
{% block content %}
	<section>
		<h2>Programming Blogs</h2>
		{% for post in posts.items %}
			<div class='post brand-background'>
				<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
				<div class='post-data'>
					Author: <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="post-data-line">{{ post.author.username }}</a>
					Date Posted: <small class="text-quiet post-data-line">{{ post.get_formatted_date(format) }}</small>
				</div>
				<div class="post-body">
					{# url_for takes the name of the roiute function and then you can set the parameters here, see below #}
					<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
					<p class="article-content">{{ post.content }}</p>
				</div>
			</div>
		{% endfor %}
		<div style="text-align: center;">
			{% for page_num in posts.iter_pages(left_edge=1, left_current=1, right_current=2, right_edge=1) %}
				{% if page_num %}
					{% if posts.page == page_num %}
						<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num, show=show) }}">{{ page_num }}</a>
					{% else %}
						<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num, show=show) }}">{{ page_num }}</a>
					{% endif %}
				{% else %}
					.  .  .
				{% endif %}
			{% endfor %}
		</div>
	</section>
{% endblock content %}

flaskblog/templates/login.html
{% extends "layout.html" %}

{% block content %}
<h1>Login</h1>
<div class="content-section">
	<!-- emtpy action means the data will be posted to the same route -->
	<form method="POST" action=""> 
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="mb-4">Log In</legend>

			<!-- EMAIL -->
			<div class="form-group sp-form">

				{{ form.email.label(class="form-control-label") }}

				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}

			</div>

			<!-- PASSWORD -->
			<div class="form-group sp-form">
				{{ form.password.label(class="form-control-label") }}

				{% if form.password.errors %}
					{{ form.password(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.password(class="form-control form-control-lg") }}
				{% endif %}

			</div>

			<div>
				<div class="form-check sp-form">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</div>

		</fieldset>

		<div class ="form-group sp-form">
			{{ form.submit(class="btn btn-outline-info" )}}
		</div>

		<small class="muted ml-2">
			<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
		</small>

	</form>
</div>

<div>
	<!-- url_for method is being passed the route METHOD name not the name of the route -->
	<small class="text-muted">Need an account?</small> <a class="ml-2" href="{{ url_for('users.reg') }}">Sign Up Here</a>
</div> 

{% endblock content %}

flaskblog/templates/modal.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- End Required for Bootstrap -->

  {% if title %}
    <title>Flask Blog - {{ title }}</title>
  {% else %}
    <title>Flask Blog</title>
  {% endif %}

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<body>
<div>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" style="display:flex;" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <section>
    <h2>Blog Post</h2>
    <div class='post'>
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class='post-data'>
        Author: <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="post-data-line">{{ post.author.username }}</a>
        Date Posted: <small class="text-quiet post-data-line">{{ post.get_formatted_date(format) }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-primary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>            
          </div>
        {% endif %}
          {# MODAL #}
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                      <input class="btn btn-danger" type="submit" value="Delete">
                    </form>

                  </div>
                </div>
              </div>
            </div>
      </div>
      <div class='post-body'>
        <h3 class="article-title">{{ post.title }}</h3>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </section>
{% endblock content %}

flaskblog/templates/reset_password.html
{% extends "layout.html" %}

{% block content %}
<h1>Reset Password</h1>
<div class="content-section">
	<!-- emtpy action means the data will be posted to the same route -->
	<form method="POST" action=""> 
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="mb-4">Reset Password</legend>

			<!-- EMAIL -->
			<div class="form-group sp-form">

				{{ form.email.label(class="form-control-label") }}

				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}

			</div>
		</fieldset>

		<div class ="form-group sp-form">
			{{ form.submit(class="btn btn-outline-info" )}}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<h1>Reset Password</h1>
<div class="content-section">
	<!-- emtpy action means the data will be posted to the same route -->
	<form method="POST" action=""> 
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="mb-4">Reset Password</legend>

			<!-- EMAIL -->
			<div class="form-group sp-form">

				{{ form.email.label(class="form-control-label") }}

				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}

			</div>
		</fieldset>

		<div class ="form-group sp-form">
			{{ form.submit(class="btn btn-outline-info" )}}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}

{% block content %}
<h1>Reset Password</h1>
<div class="content-section">
	<!-- emtpy action means the data will be posted to the same route -->
	<form method="POST" action=""> 
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="mb-4">Reset Password</legend>

			<!-- PASSWORD -->
			<div class="form-group sp-form">

				{{ form.password.label(class="form-control-label") }}

				{% if form.password.errors %}
					{{ form.password(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.password(class="form-control form-control-lg") }}
				{% endif %}

			</div>

			<!-- CONFIRM PASSWORD -->
			<div class="form-group sp-form">

				{{ form.confirm_password.label(class="form-control-label") }}

				{% if form.confirm_password.errors %}
					{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.confirm_password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.confirm_password(class="form-control form-control-lg") }}
				{% endif %}

			</div>
		</fieldset>

		<div class ="form-group sp-form">
			{{ form.submit(class="btn btn-outline-info" )}}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/test.html
<!DOCTYPE html>
<html>
	<head>
		<title>TEST</title>
	</head>
	<body>
		<header id="site-header" class="brand-background">
			<div class="boite">
				<h1>Flask Blog</h1>
			</div>
		</header>
		
		<div class="brand-background">SOMETHING SOMETHING SOMETHING</div>
		<div>SOMETHING</div>
		<div>I don't know.</div>
		<div class="brand-background">BLAH</div>
	</body>
</html>

flaskblog/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
	<section>
		<h2>Posts by {{ user.username }} ({{ posts.total }})</h2>
		{% for post in posts.items %}
			<div class='post brand-background'>
				<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
				<div class='post-data'>
					Author: <a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="post-data-line">{{ post.author.username }}</a>
					Date Posted: <small class="text-quiet post-data-line">{{ post.get_formatted_date(format) }}</small>
				</div>
				<div class="post-body">
					{# url_for takes the name of the roiute function and then you can set the parameters here, see below #}
					<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
					<p class="article-content">{{ post.content }}</p>
				</div>
			</div>
		{% endfor %}
		<div style="text-align: center;">
			{% for page_num in posts.iter_pages(left_edge=1, left_current=1, right_current=2, right_edge=1) %}
				{% if page_num %}
					{% if posts.page == page_num %}
						<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=username, page=page_num) }}">{{ page_num }}</a>
					{% else %}
						<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=username, page=page_num) }}">{{ page_num }}</a>
					{% endif %}
				{% else %}
					.  .  .
				{% endif %}
			{% endfor %}
		</div>
	</section>
{% endblock content %}

flaskblog/templates/workorder.html
{% extends "layout.html" %}
{% block content %}

	<section class='container'>
		<h2>WORK ORDER PAGE</h2>
		<h3>{{ workordernumber }}</h3>
	</section>
{% endblock content %}